name: Rust Test Suite

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/*_rust.yml
      - src/**
      - tests/**
      - Cargo.lock
      - Cargo.toml
      - deny.toml
  pull_request:
    paths:
      - .github/workflows/*_rust.yml
      - src/**
      - tests/**
      - Cargo.lock
      - Cargo.toml
      - deny.toml

permissions:
  contents: read

jobs:
  test:
    name: Rust test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: lang-rust-${{runner.os}}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: cargo-llvm-cov
      - name: Run Cargo Clippy
        run: cargo clippy
      - name: Run Cargo Fmt
        run: cargo fmt --check
      - name: Run Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Generate coverage report from Rust tests
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info
      - name: Run examples
        run: |
          cargo run --example async_auto_fix
          cargo run --example async_check
          cargo run --example auto_fix
          cargo run --example check
      - name: Run doc tests
        run: cargo test --doc
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: lcov.info
          flags: lang-rust
